=== IamTheDoctor17/StarThief/src/main/assets/core/core/planet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
   xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="posx" type="xs:int"/>
                <xs:element name="posy" type="xs:int"/>
                <xs:element name="width" type="xs:int"/>
                <xs:element name="height" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="entity">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="entities">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entity" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

   <xs:element name="level">
   	<xs:complexType>
		<xs:sequence>
            <xs:element ref="entities"/>
            <xs:element ref="items"/>
        </xs:sequence>
   		<xs:attribute name="mapurl" type="xs:string" use="required"/>
        <xs:attribute name="playerStartX" type="xs:int" use="required"/>
        <xs:attribute name="playerStartY" type="xs:int" use="required"/>
   	</xs:complexType>
   </xs:element>

    <xs:element name="meta">
        <xs:complexType>
            <xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

   <xs:element name="planet" >
   	<xs:complexType>
   		<xs:sequence>
            <xs:element ref="meta"/>
            <xs:element ref="level" maxOccurs="unbounded" />
   		</xs:sequence>
   		<xs:attribute name="name" type="xs:string" use="required"/>
   	</xs:complexType>
   </xs:element>
</xs:schema>

=== IamTheDoctor17/StarThief/src/main/assets/core/planets/testplanet/planet.xml
<?xml version="1.0" encoding="UTF-8"?>
<planet
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:noNamespaceSchemaLocation="../../core/planet.xsd" name="testplanet">
    <level mapurl="level/level1.tmx" playerStartX="200" playerStartY="200">
        <entities>
            <entity id="simple_entity">
                <data>
                    <posx>500</posx>
                    <posy>500</posy>
                    <width>60</width>
                    <height>60</height>
                </data>
            </entity>
        </entities>
        <items>
            <item id="1">
                <data>
                    <posx>50</posx>
                    <posy>50</posy>
                </data>
            </item>
        </items>
    </level>
    <level mapurl="level/level2.tmx" playerStartX="200" playerStartY="200">
    </level>
</planet>

=== IamTheDoctor17/StarThief/src/main/assets/core/planets/testplanet2/planet.xml
<?xml version="1.0" encoding="utf-8" ?>
<planet
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:noNamespaceSchemaLocation="../../core/planet.xsd" name="testplanet2">
    <level mapurl="level/level1.tmx" playerStartX="480" playerStartY="544">
        <entities>
            <entity id="simple_entity">
                <data>
                    <posx>896</posx>
                    <posy>608</posy>
                    <width>50</width>
                    <height>50</height>
                </data>
            </entity>
        </entities>
    </level>
    <level mapurl="level/level1.xml" playerStartX="480" playerStartY="544">
        <entities>
            <entity id="simple_entity">
                <data>
                    <posx>896</posx>
                    <posy>608</posy>
                    <width>50</width>
                    <height>50</height>
                </data>
            </entity></entities>
    </level>
</planet>
