=== IamTheDoctor17/StarThief/src/main/assets/core/models/simpleentity.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="posx" type="xs:int"/>
                <xs:element name="posy" type="xs:int"/>
                <xs:element name="width" type="xs:int"/>
                <xs:element name="height" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="location" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="simpleentity">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resource"/>
                <xs:element ref="data"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IamTheDoctor17/StarThief/src/main/assets/core/models/simpleentity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simpleentity xs:noNamespaceSchemaLocation="simpleentity.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
    <resource>
        <location>textures/simpleentity.png</location>
    </resource>
    <data>
        <posx>150</posx>
        <posy>100</posy>
        <width>60</width>
        <height>60</height>
    </data>
</simpleentity>
